### ISSUE TITLE
Normalize a spectrum

### ISSUE THREAD

**Issue by DanielAndreasen** [jason-neal/spectrum_overload#31]
I'm not sure if this is within the scope of this project, but I can definitely see the usecases of being able to normalize a spectrum. Maybe something like:

```python
s = Spectrum(flux, xaxis=wavelength)
s.normalize('linear')
# or
s.normalize('polynomial', degree=n)  # 'linear' kan be a subset of this
# or
s.normalize('spline')
```

What do you think about it?
If you are going to implement interpolation (issue #3), then you are not far away from a normalization method.

**Comment by jason-neal** [comment]
Yes that could fit. I have some normalization stuff that I can adapt from [companion_simulations](https://github.com/jason-neal/companion_simulations/blob/develop/utilities/norm.py)

**Comment by DanielAndreasen** [comment]
Cool, I definitely think this can be used. Didn't have a look through all your code and branches.

**Comment by jason-neal** [comment]
@DanielAndreasen  PR #38  attempts to implement the normalization. 
If you have something you want/need to normalize let me know how it goes.

**Comment by DanielAndreasen** [comment]
I guess you need to correct a little to make CI build it, otherwise it looks nice :+1: I don't have anything to test it with right now though.

**Comment by jason-neal** [comment]
This issues are tests not related to normalization that I am working on it a different branch.
