### ISSUE TITLE
from spectrum_overload.Spectrum import Spectrum

### ISSUE THREAD

**Issue by DanielAndreasen** [jason-neal/spectrum_overload#75]
This doesn't work, and it is written in the README, documentation, and maybe even other places. Should be changed from:
`from spectrum_overload.Spectrum import Spectrum`
to
`from spectrum_overload import Spectrum`

**Comment by jason-neal** [comment]
Ah thanks, I changed the case of the spectrum module from Spectrum to spectrum.
